-- classic track seed: verbatim Project Gutenberg extracts (US public domain),
-- generated 2026-07-10 by scripts documented in AGENTS.md. Do not hand-edit texts.

INSERT OR IGNORE INTO articles (id, url, title, source, track, license, attribution, published_at, fetched_at) VALUES ('gutenberg-205-walden', 'https://www.gutenberg.org/ebooks/205', 'Walden', 'gutenberg', 'classic', 'public-domain', 'Henry David Thoreau, Walden (1854) — public domain', NULL, datetime('now'));
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 0, 'I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived. I did not wish to live what was not life, living is so dear; nor did I wish to practise resignation, unless it was quite necessary.', 70);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 1, 'I wanted to live deep and suck out all the marrow of life, to live so sturdily and Spartan-like as to put to rout all that was not life, to cut a broad swath and shave close, to drive life into a corner, and reduce it to its lowest terms, and, if it proved to be mean, why then to get the whole and genuine meanness of it, and publish its meanness to the world; or if it were sublime, to know it by experience, and be able to give a true account of it in my next excursion.', 99);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 2, 'For most men, it appears to me, are in a strange uncertainty about it, whether it is of the devil or of God, and have somewhat hastily concluded that it is the chief end of man here to "glorify God and enjoy him forever."', 44);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 3, 'Still we live meanly, like ants; though the fable tells us that we were long ago changed into men; like pygmies we fight with cranes; it is error upon error, and clout upon clout, and our best virtue has for its occasion a superfluous and evitable wretchedness. Our life is frittered away by detail. An honest man has hardly need to count more than his ten fingers, or in extreme cases he may add his ten toes, and lump the rest. Simplicity, simplicity, simplicity!', 84);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 4, 'I say, let your affairs be as two or three, and not a hundred or a thousand; instead of a million count half a dozen, and keep your accounts on your thumb nail.', 33);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 5, 'In the midst of this chopping sea of civilized life, such are the clouds and storms and quicksands and thousand-and-one items to be allowed for, that a man has to live, if he would not founder and go to the bottom and not make his port at all, by dead reckoning, and he must be a great calculator indeed who succeeds. Simplify, simplify.', 63);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 6, 'Instead of three meals a day, if it be necessary eat but one; instead of a hundred dishes, five; and reduce other things in proportion. Our life is like a German Confederacy, made up of petty states, with its boundary forever fluctuating, so that even a German cannot tell you how it is bounded at any moment.', 57);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 7, 'The nation itself, with all its so called internal improvements, which, by the way, are all external and superficial, is just such an unwieldy and overgrown establishment, cluttered with furniture and tripped up by its own traps, ruined by luxury and heedless expense, by want of calculation and a worthy aim, as the million households in the land; and the only cure for it as for them is in a rigid economy, a stern and more than Spartan simplicity of life and elevation of purpose.', 85);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 8, 'It lives too fast. Men think that it is essential that the Nation have commerce, and export ice, and talk through a telegraph, and ride thirty miles an hour, without a doubt, whether they do or not; but whether we should live like baboons or like men, is a little uncertain. If we do not get out sleepers, and forge rails, and devote days and nights to the work, but go to tinkering upon our lives to improve them, who will build railroads?', 83);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 9, 'And if railroads are not built, how shall we get to heaven in season? But if we stay at home and mind our business, who will want railroads? We do not ride on the railroad; it rides upon us. Did you ever think what those sleepers are that underlie the railroad? Each one is a man, an Irish-man, or a Yankee man. The rails are laid on them, and they are covered with sand, and the cars run smoothly over them.', 81);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 10, 'They are sound sleepers, I assure you. And every few years a new lot is laid down and run over; so that, if some have the pleasure of riding on a rail, others have the misfortune to be ridden upon. And when they run over a man that is walking in his sleep, a supernumerary sleeper in the wrong position, and wake him up, they suddenly stop the cars, and make a hue and cry about it, as if this were an exception.', 83);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 11, 'I am glad to know that it takes a gang of men for every five miles to keep the sleepers down and level in their beds as it is, for this is a sign that they may sometime get up again.', 41);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 12, 'The mass of men lead lives of quiet desperation. What is called resignation is confirmed desperation. From the desperate city you go into the desperate country, and have to console yourself with the bravery of minks and muskrats. A stereotyped but unconscious despair is concealed even under what are called the games and amusements of mankind. There is no play in them, for this comes after work. But it is a characteristic of wisdom not to do desperate things.', 79);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 13, 'Time is but the stream I go a-fishing in. I drink at it; but while I drink I see the sandy bottom and detect how shallow it is. Its thin current slides away, but eternity remains. I would drink deeper; fish in the sky, whose bottom is pebbly with stars. I cannot count one. I know not the first letter of the alphabet. I have always been regretting that I was not as wise as the day I was born.', 80);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 14, 'The intellect is a cleaver; it discerns and rifts its way into the secret of things. I do not wish to be any more busy with my hands than is necessary. My head is hands and feet. I feel all my best faculties concentrated in it. My instinct tells me that my head is an organ for burrowing, as some creatures use their snout and fore-paws, and with it I would mine and burrow my way through these hills.', 79);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-205-walden', 15, 'I think that the richest vein is somewhere hereabouts; so by the divining-rod and thin rising vapors I judge; and here I will begin to mine.', 26);

INSERT OR IGNORE INTO articles (id, url, title, source, track, license, attribution, published_at, fetched_at) VALUES ('gutenberg-16643-self-reliance', 'https://www.gutenberg.org/ebooks/16643', 'Self-Reliance (Essays: First Series)', 'gutenberg', 'classic', 'public-domain', 'Ralph Waldo Emerson, Self-Reliance (1841) — public domain', NULL, datetime('now'));
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 0, 'There is a time in every man''s education when he arrives at the conviction that envy is ignorance; that imitation is suicide;[154] that he must take himself for better, for worse, as his portion; that though the wide universe is full of good, no kernel of nourishing corn can come to him but through his toil bestowed on that plot of ground which is given to him to till.', 69);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 1, 'The power which resides in him is new in nature, and none but he knows what that is which he can do, nor does he know until he has tried. Not for nothing one face, one character, one fact, makes much impression on him, and another none. This sculpture in the memory is not without preëstablished harmony. The eye was placed where one ray should fall, that it might testify of that particular ray.', 74);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 2, 'We but half express ourselves,[155] and are ashamed of that divine idea which each of us represents. It may be safely trusted as proportionate and of good issues, so it be faithfully imparted, but God will not have his work made manifest by cowards. A man is relieved and gay when he has put his heart into his work and done his best; but what he has said or done otherwise shall give him no peace. It is a deliverance which does not deliver. In the attempt his genius deserts him; no muse befriends; no invention, no hope.', 98);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 3, 'Whoso would be a man must be a nonconformist.[165] He who would gather immortal palms must not be hindered by the name of goodness, but must explore if it be goodness.[166] Nothing is at last sacred but the integrity of your own mind. Absolve you to yourself, and you shall have the suffrage[167] of the world.', 56);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 4, 'I remember an answer which when quite young I was prompted to make to a valued adviser, who was wont to importune me with the dear old doctrines of the church. On my saying, What have I to do with the sacredness of traditions, if I live wholly from within?', 50);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 5, 'my friend suggested: "But these impulses may be from below, not from above." I replied: "They do not seem to me to be such; but if I am the Devil''s child, I will live then from the Devil." No law can be sacred to me but that of my nature. Good and bad are but names very readily transferable to that or this;[168] the only right is what is after my constitution, the only wrong what is against it.', 79);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 6, 'A man is to carry himself in the presence of all opposition, as if everything were titular and ephemeral but he. I am ashamed to think how easily we capitulate to badges and names, to large societies and dead institutions. Every decent and well-spoken individual affects and sways me more than is right. I ought to go upright and vital, and speak the rude truth in all ways. If malice and vanity wear the coat of philanthropy, shall that pass?', 80);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 7, 'If an angry bigot assumes this bountiful cause of Abolition, and comes to me with his last news from Barbadoes,[169] why should I not say to him: "Go love thy infant; love thy wood-chopper: be good-natured and modest: have that grace; and never varnish your hard, uncharitable ambition with this incredible tenderness for black folk a thousand miles off. Thy love afar is spite at home." Rough and graceless would be such greeting, but truth is handsomer than the affectation of love.', 82);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 8, 'Your goodness must have some edge to it,--else it is none. The doctrine of hatred must be preached as the counteraction of the doctrine of love when that pules and whines. I shun father and mother and wife and brother, when my genius calls me. I would write on the lintels of the door-post, Whim.[170] I hope it is somewhat better than whim at last, but we cannot spend the day in explanation.', 73);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 9, 'Expect me not to show cause why I seek or why I exclude company. Then, again, do not tell me, as a good man did to-day, of my obligation to put all poor men in good situations. Are they my poor? I tell thee, thou foolish philanthropist, that I grudge the dollar, the dime, the cent, I give to such men as do not belong to me and to whom I do not belong.', 74);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 10, 'There is a class of persons to whom by all spiritual affinity I am bought and sold; for them I will go to prison, if need be; but your miscellaneous popular charities; the education at college of fools; the building of meeting-houses to the vain end to which many now stand; alms to sots; and the thousand-fold Relief Societies;--though I confess with shame I sometimes succumb and give the dollar, it is a wicked dollar which by and by I shall have the manhood to withhold.', 86);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 11, 'A foolish consistency is the hobgoblin of little minds, adored by little statesmen and philosophers and divines. With consistency a great soul has simply nothing to do. He may as well concern himself with the shadow on the wall. Speak what you think now in hard words, and to-morrow speak what to-morrow thinks in hard words again, though it contradict everything you said to-day.--"Ah, so you shall be sure to be misunderstood."--Is it so bad, then, to be misunderstood?', 79);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-16643-self-reliance', 12, 'Pythagoras[186] was misunderstood, and Socrates,[187] and Jesus, and Luther,[188] and Copernicus,[189] and Galileo,[190] and Newton,[191] and every pure and wise spirit that ever took flesh. To be great is to be misunderstood.', 32);

INSERT OR IGNORE INTO articles (id, url, title, source, track, license, attribution, published_at, fetched_at) VALUES ('gutenberg-5827-problems-philosophy', 'https://www.gutenberg.org/ebooks/5827', 'The Problems of Philosophy', 'gutenberg', 'classic', 'public-domain', 'Bertrand Russell, The Problems of Philosophy (1912) — public domain', NULL, datetime('now'));
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-5827-problems-philosophy', 0, 'The value of philosophy is, in fact, to be sought largely in its very uncertainty. The man who has no tincture of philosophy goes through life imprisoned in the prejudices derived from common sense, from the habitual beliefs of his age or his nation, and from convictions which have grown up in his mind without the co-operation or consent of his deliberate reason.', 63);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-5827-problems-philosophy', 1, 'To such a man the world tends to become definite, finite, obvious; common objects rouse no questions, and unfamiliar possibilities are contemptuously rejected. As soon as we begin to philosophize, on the contrary, we find, as we saw in our opening chapters, that even the most everyday things lead to problems to which only very incomplete answers can be given.', 60);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-5827-problems-philosophy', 2, 'Philosophy, though unable to tell us with certainty what is the true answer to the doubts which it raises, is able to suggest many possibilities which enlarge our thoughts and free them from the tyranny of custom.', 37);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-5827-problems-philosophy', 3, 'Thus, while diminishing our feeling of certainty as to what things are, it greatly increases our knowledge as to what they may be; it removes the somewhat arrogant dogmatism of those who have never travelled into the region of liberating doubt, and it keeps alive our sense of wonder by showing familiar things in an unfamiliar aspect.', 57);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-5827-problems-philosophy', 4, 'Thus, to sum up our discussion of the value of philosophy; Philosophy is to be studied, not for the sake of any definite answers to its questions, since no definite answers can, as a rule, be known to be true, but rather for the sake of the questions themselves; because these questions enlarge our conception of what is possible, enrich our intellectual imagination and diminish the dogmatic assurance which closes the mind against speculation; but above all because, through the greatness of the universe which philosophy contemplates, the mind also is rendered great, and becomes capable of that union with the universe which constitutes its highest good.', 107);

INSERT OR IGNORE INTO articles (id, url, title, source, track, license, attribution, published_at, fetched_at) VALUES ('gutenberg-148-franklin', 'https://www.gutenberg.org/ebooks/148', 'The Autobiography of Benjamin Franklin', 'gutenberg', 'classic', 'public-domain', 'Benjamin Franklin, Autobiography (1791) — public domain', NULL, datetime('now'));
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-148-franklin', 0, 'It was about this time I conceiv''d the bold and arduous project of arriving at moral perfection. I wish''d to live without committing any fault at any time; I would conquer all that either natural inclination, custom, or company might lead me into. As I knew, or thought I knew, what was right and wrong, I did not see why I might not always do the one and avoid the other.', 71);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-148-franklin', 1, 'But I soon found I had undertaken a task of more difficulty than I had imagined. While my care was employ''d in guarding against one fault, I was often surprised by another; habit took the advantage of inattention; inclination was sometimes too strong for reason.', 45);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-148-franklin', 2, 'I concluded, at length, that the mere speculative conviction that it was our interest to be completely virtuous, was not sufficient to prevent our slipping; and that the contrary habits must be broken, and good ones acquired and established, before we can have any dependence on a steady, uniform rectitude of conduct. For this purpose I therefore contrived the following method.', 61);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-148-franklin', 3, 'In the various enumerations of the moral virtues I had met with in my reading, I found the catalogue more or less numerous, as different writers included more or fewer ideas under the same name. Temperance, for example, was by some confined to eating and drinking, while by others it was extended to mean the moderating every other pleasure, appetite, inclination, or passion, bodily or mental, even to our avarice and ambition.', 72);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count) VALUES ('gutenberg-148-franklin', 4, 'I propos''d to myself, for the sake of clearness, to use rather more names, with fewer ideas annex''d to each, than a few names with more ideas; and I included under thirteen names of virtues all that at that time occurr''d to me as necessary or desirable, and annexed to each a short precept, which fully express''d the extent I gave to its meaning.', 64);
