-- code track seed: idiomatic snippets, original content (CC0).
-- Generated by scripts/gen_code_seed.py - regenerate, don't hand-edit.

INSERT OR IGNORE INTO articles (id, url, title, source, track, license, attribution, published_at, fetched_at) VALUES ('code-python', '', 'Python snippets', 'authored', 'code', 'cc0', 'idiomatic Python — original snippets (CC0)', NULL, datetime('now'));
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-python', 0, 'def fib(n: int) -> int:
  a, b = 0, 1
  for _ in range(n):
    a, b = b, a + b
  return a', 23, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-python', 1, 'with open("log.txt") as f:
  lines = [line.strip() for line in f]
print(len(lines), "lines")', 13, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-python', 2, 'from collections import Counter

def top_words(text, k=3):
  words = text.lower().split()
  return Counter(words).most_common(k)', 12, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-python', 3, 'class Stack:
  def __init__(self):
    self.items = []
  def push(self, x):
    self.items.append(x)
  def pop(self):
    return self.items.pop()', 15, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-python', 4, 'squares = {n: n * n for n in range(10) if n % 2 == 0}
for k, v in sorted(squares.items()):
  print(f"{k} squared is {v}")', 25, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-python', 5, 'import json

def load_config(path):
  try:
    with open(path) as f:
      return json.load(f)
  except FileNotFoundError:
    return {}', 15, -1);

INSERT OR IGNORE INTO articles (id, url, title, source, track, license, attribution, published_at, fetched_at) VALUES ('code-rust', '', 'Rust snippets', 'authored', 'code', 'cc0', 'idiomatic Rust — original snippets (CC0)', NULL, datetime('now'));
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-rust', 0, 'fn main() {
  let nums = vec![3, 1, 4, 1, 5, 9];
  let sum: i32 = nums.iter().sum();
  println!("sum = {sum}");
}', 21, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-rust', 1, 'fn largest(list: &[i32]) -> Option<&i32> {
  list.iter().max()
}', 8, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-rust', 2, 'struct Point {
  x: f64,
  y: f64,
}

impl Point {
  fn dist(&self) -> f64 {
    (self.x * self.x + self.y * self.y).sqrt()
  }
}', 25, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-rust', 3, 'let words = ["alpha", "beta", "gamma"];
let joined = words
  .iter()
  .filter(|w| w.len() > 4)
  .cloned()
  .collect::<Vec<_>>()
  .join(", ");', 19, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-rust', 4, 'match value {
  0 => println!("zero"),
  n if n < 0 => println!("negative"),
  _ => println!("positive"),
}', 17, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-rust', 5, 'use std::collections::HashMap;

let mut counts: HashMap<char, u32> = HashMap::new();
for c in "banana".chars() {
  *counts.entry(c).or_insert(0) += 1;
}', 18, -1);

INSERT OR IGNORE INTO articles (id, url, title, source, track, license, attribution, published_at, fetched_at) VALUES ('code-go', '', 'Go snippets', 'authored', 'code', 'cc0', 'idiomatic Go — original snippets (CC0)', NULL, datetime('now'));
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-go', 0, 'func sum(nums []int) int {
  total := 0
  for _, n := range nums {
    total += n
  }
  return total
}', 22, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-go', 1, 'func main() {
  ch := make(chan string)
  go func() { ch <- "done" }()
  fmt.Println(<-ch)
}', 16, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-go', 2, 'type User struct {
  Name string
  Age  int
}

func (u User) Greet() string {
  return "hello, " + u.Name
}', 21, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-go', 3, 'if err := run(); err != nil {
  log.Fatalf("run failed: %v", err)
}', 13, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-go', 4, 'counts := map[string]int{}
for _, w := range strings.Fields(text) {
  counts[w]++
}', 12, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-go', 5, 'func reverse(s string) string {
  r := []rune(s)
  for i, j := 0, len(r)-1; i < j; i, j = i+1, j-1 {
    r[i], r[j] = r[j], r[i]
  }
  return string(r)
}', 32, -1);

INSERT OR IGNORE INTO articles (id, url, title, source, track, license, attribution, published_at, fetched_at) VALUES ('code-java', '', 'Java snippets', 'authored', 'code', 'cc0', 'idiomatic Java — original snippets (CC0)', NULL, datetime('now'));
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-java', 0, 'public static int max(int[] xs) {
  int best = xs[0];
  for (int x : xs) {
    if (x > best) best = x;
  }
  return best;
}', 27, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-java', 1, 'List<String> names = List.of("kim", "lee", "park");
String joined = names.stream()
  .map(String::toUpperCase)
  .collect(Collectors.joining(", "));', 13, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-java', 2, 'record Point(double x, double y) {
  double dist() {
    return Math.sqrt(x * x + y * y);
  }
}', 19, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-java', 3, 'try (var reader = Files.newBufferedReader(path)) {
  return reader.lines().count();
} catch (IOException e) {
  return 0;
}', 16, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-java', 4, 'Map<String, Integer> counts = new HashMap<>();
for (String w : text.split("\\s+")) {
  counts.merge(w, 1, Integer::sum);
}', 16, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-java', 5, 'public interface Shape {
  double area();

  default String describe() {
    return "area = " + area();
  }
}', 18, -1);

INSERT OR IGNORE INTO articles (id, url, title, source, track, license, attribution, published_at, fetched_at) VALUES ('code-cpp', '', 'C++ snippets', 'authored', 'code', 'cc0', 'idiomatic C++ — original snippets (CC0)', NULL, datetime('now'));
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-cpp', 0, 'int fib(int n) {
  int a = 0, b = 1;
  while (n-- > 0) {
    int t = a + b;
    a = b;
    b = t;
  }
  return a;
}', 32, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-cpp', 1, 'std::vector<int> v{3, 1, 4, 1, 5};
std::sort(v.begin(), v.end());
for (int x : v) {
  std::cout << x << " ";
}', 21, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-cpp', 2, 'struct Point {
  double x, y;
  double dist() const {
    return std::sqrt(x * x + y * y);
  }
};', 20, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-cpp', 3, 'std::map<char, int> counts;
for (char c : text) {
  ++counts[c];
}', 11, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-cpp', 4, 'auto square = [](int n) { return n * n; };
std::transform(v.begin(), v.end(), v.begin(), square);', 15, -1);
INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) VALUES ('code-cpp', 5, 'template <typename T>
T clamp(T v, T lo, T hi) {
  return v < lo ? lo : (v > hi ? hi : v);
}', 26, -1);
