#!/usr/bin/env python3
"""Generate migrations/0011_code_seed.sql — idiomatic code snippets.

All snippets are original, written for this project (CC0): C++, Java, Python,
Go, Rust (Director's pick, 2026-07-12). One snippet = one passage; newlines
are real so the engine's Enter support gets exercised; 2-space indentation,
no tabs. fk_grade is seeded as -1 (unscorable sentinel) so difficulty-range
filters never match code and the cron backfill skips it. Regenerate with:
  python3 scripts/gen_code_seed.py > migrations/0011_code_seed.sql
"""

SNIPPETS = {
    "python": [
        'def fib(n: int) -> int:\n  a, b = 0, 1\n  for _ in range(n):\n    a, b = b, a + b\n  return a',
        'with open("log.txt") as f:\n  lines = [line.strip() for line in f]\nprint(len(lines), "lines")',
        'from collections import Counter\n\ndef top_words(text, k=3):\n  words = text.lower().split()\n  return Counter(words).most_common(k)',
        'class Stack:\n  def __init__(self):\n    self.items = []\n  def push(self, x):\n    self.items.append(x)\n  def pop(self):\n    return self.items.pop()',
        'squares = {n: n * n for n in range(10) if n % 2 == 0}\nfor k, v in sorted(squares.items()):\n  print(f"{k} squared is {v}")',
        'import json\n\ndef load_config(path):\n  try:\n    with open(path) as f:\n      return json.load(f)\n  except FileNotFoundError:\n    return {}',
    ],
    "rust": [
        'fn main() {\n  let nums = vec![3, 1, 4, 1, 5, 9];\n  let sum: i32 = nums.iter().sum();\n  println!("sum = {sum}");\n}',
        'fn largest(list: &[i32]) -> Option<&i32> {\n  list.iter().max()\n}',
        'struct Point {\n  x: f64,\n  y: f64,\n}\n\nimpl Point {\n  fn dist(&self) -> f64 {\n    (self.x * self.x + self.y * self.y).sqrt()\n  }\n}',
        'let words = ["alpha", "beta", "gamma"];\nlet joined = words\n  .iter()\n  .filter(|w| w.len() > 4)\n  .cloned()\n  .collect::<Vec<_>>()\n  .join(", ");',
        'match value {\n  0 => println!("zero"),\n  n if n < 0 => println!("negative"),\n  _ => println!("positive"),\n}',
        'use std::collections::HashMap;\n\nlet mut counts: HashMap<char, u32> = HashMap::new();\nfor c in "banana".chars() {\n  *counts.entry(c).or_insert(0) += 1;\n}',
    ],
    "go": [
        'func sum(nums []int) int {\n  total := 0\n  for _, n := range nums {\n    total += n\n  }\n  return total\n}',
        'func main() {\n  ch := make(chan string)\n  go func() { ch <- "done" }()\n  fmt.Println(<-ch)\n}',
        'type User struct {\n  Name string\n  Age  int\n}\n\nfunc (u User) Greet() string {\n  return "hello, " + u.Name\n}',
        'if err := run(); err != nil {\n  log.Fatalf("run failed: %v", err)\n}',
        'counts := map[string]int{}\nfor _, w := range strings.Fields(text) {\n  counts[w]++\n}',
        'func reverse(s string) string {\n  r := []rune(s)\n  for i, j := 0, len(r)-1; i < j; i, j = i+1, j-1 {\n    r[i], r[j] = r[j], r[i]\n  }\n  return string(r)\n}',
    ],
    "java": [
        'public static int max(int[] xs) {\n  int best = xs[0];\n  for (int x : xs) {\n    if (x > best) best = x;\n  }\n  return best;\n}',
        'List<String> names = List.of("kim", "lee", "park");\nString joined = names.stream()\n  .map(String::toUpperCase)\n  .collect(Collectors.joining(", "));',
        'record Point(double x, double y) {\n  double dist() {\n    return Math.sqrt(x * x + y * y);\n  }\n}',
        'try (var reader = Files.newBufferedReader(path)) {\n  return reader.lines().count();\n} catch (IOException e) {\n  return 0;\n}',
        'Map<String, Integer> counts = new HashMap<>();\nfor (String w : text.split("\\\\s+")) {\n  counts.merge(w, 1, Integer::sum);\n}',
        'public interface Shape {\n  double area();\n\n  default String describe() {\n    return "area = " + area();\n  }\n}',
    ],
    "cpp": [
        'int fib(int n) {\n  int a = 0, b = 1;\n  while (n-- > 0) {\n    int t = a + b;\n    a = b;\n    b = t;\n  }\n  return a;\n}',
        'std::vector<int> v{3, 1, 4, 1, 5};\nstd::sort(v.begin(), v.end());\nfor (int x : v) {\n  std::cout << x << \" \";\n}',
        'struct Point {\n  double x, y;\n  double dist() const {\n    return std::sqrt(x * x + y * y);\n  }\n};',
        'std::map<char, int> counts;\nfor (char c : text) {\n  ++counts[c];\n}',
        'auto square = [](int n) { return n * n; };\nstd::transform(v.begin(), v.end(), v.begin(), square);',
        'template <typename T>\nT clamp(T v, T lo, T hi) {\n  return v < lo ? lo : (v > hi ? hi : v);\n}',
    ],
}

LABELS = {"python": "Python", "rust": "Rust", "go": "Go", "java": "Java", "cpp": "C++"}


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def main() -> None:
    print("-- code track seed: idiomatic snippets, original content (CC0).")
    print("-- Generated by scripts/gen_code_seed.py - regenerate, don't hand-edit.")
    for lang, snippets in SNIPPETS.items():
        art_id = f"code-{lang}"
        title = f"{LABELS[lang]} snippets"
        print(
            f"\nINSERT OR IGNORE INTO articles (id, url, title, source, track, license, attribution, published_at, fetched_at) "
            f"VALUES ('{art_id}', '', '{title}', 'authored', 'code', 'cc0', "
            f"'idiomatic {LABELS[lang]} — original snippets (CC0)', NULL, datetime('now'));"
        )
        for seq, code in enumerate(snippets):
            wc = len(code.split())
            print(
                f"INSERT OR IGNORE INTO passages (article_id, seq, text, word_count, fk_grade) "
                f"VALUES ('{art_id}', {seq}, '{sql_escape(code)}', {wc}, -1);"
            )


if __name__ == "__main__":
    main()
